development:
    adapter: postgresql
    database: prelaunchr_development
    host: localhost    
    pool: 5
    username: postgres
    password: root
test:
    adapter: postgresql
    database: prelaunchr_test
    host: localhost
    pool: 5
    username: postgres
    password: root

production:
	adapter: postgresql
	database: prelaunchr_test
	host: localhost
	pool: 5
	username: postgres
	password: root
